### PR TITLE
Feature/create dir error

### PR DESCRIPTION
**Pull request by pinin4fjords**
This PR addresses current issue where error is produced with pre-existing output directories

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Sorry, the README thing shouldn't be there...

**Comment by a-solovyev12** [comment]
this is something I should have considered - thanks @pinin4fjords

**Review by a-solovyev12 — APPROVED** [review]

**Comment by pinin4fjords** [comment]
No worries. Could you sort a release for this please @a-solovyev12 ?

**Comment by a-solovyev12** [comment]
sure! @pinin4fjords

**Pull request merged**
